import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/Button';
import Gradient from '../components/Gradient';
import Wrapper from '../components/Layout/Wrapper';
import Heading from '../components/Typography/Heading';
import Paragraph from '../components/Typography/Paragraph';
import { GithubIcon, LinkedinIcon, TwitterIcon } from '../components/Icon/Social';
import Navbar from '../components/Navbar';
import BlogCard from '../components/Card/Blog';
import Footer from '../components/Footer';
import { useSocials } from '../hooks/useSocials';

const Home: NextPage = () => {
  const { socials } = useSocials();

  const fakeCard = {
    date: new Date(),
    title: 'Lorem Ipsum',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mattis orci rutrum pulvinar nisl, quam neque in.',
    url: '/test',
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png" />
      </Head>

      <Navbar />

      <main className="overflow-x-hidden">
        <Wrapper className="relative">
          <div className="relative z-10 space-y-10">
            <Heading level={1}>Developer creating smooth, thoughtful user interfaces</Heading>
            <Paragraph>
              Hello! I’m Simon Bellucci — front-end developer based in Strasbourg 🥨. Interested in
              cryptocurrencies, human-machine interactions, spatial computing, science and
              productivity.
            </Paragraph>
            <Paragraph>
              I’m currently working at{' '}
              <a
                href="https://adeliom.com"
                target="_blank"
                rel="noreferrer"
                className="underline transition-colors hover:text-black dark:hover:text-white"
              >
                Adeliom
              </a>{' '}
              where we’re building modern and intuitive websites.
            </Paragraph>
            <div className="item-center flex space-x-10">
              <div className="flex items-center space-x-4">
                <a href={socials.github} title="My Github account" target="_blank" rel="noreferrer">
                  <GithubIcon />
                </a>
                <a
                  href={socials.linkedin}
                  title="My Linkedin account"
                  target="_blank"
                  rel="noreferrer"
                >
                  <LinkedinIcon />
                </a>
                <a
                  href={socials.twitter}
                  title="My Twitter account"
                  target="_blank"
                  rel="noreferrer"
                >
                  <TwitterIcon />
                </a>
              </div>
              <Button onClick={() => window.open(`mailto:${socials.mail}`, '_blank')}>
                Say Hi 👋
              </Button>
            </div>
          </div>
          <Gradient className="absolute -right-64 top-12 -z-10 md:-right-48 lg:-right-24 xl:right-12" />
        </Wrapper>
        <Wrapper>
          <Heading level={2} type="h1" className="mb-5">
            Latest
          </Heading>
          <Paragraph className="border-b border-gray-300 pb-10 transition-colors dark:border-gray-600">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis dolor vestibulum, quisque
            tristique vitae odio elit est commodo. Amet cursus elit sed turpis ut. Ac scelerisque
            nibh id vitae integer non. Lectus at ullamcorper nunc amet.
          </Paragraph>
          <div className="mt-6 space-y-6 lg:mt-10 lg:space-y-10">
            <BlogCard {...fakeCard} />
            <BlogCard {...fakeCard} />
            <BlogCard {...fakeCard} />
          </div>
        </Wrapper>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
